{
 "title": "OSC cost Tenant : LNF",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "vm_resource_id",
    "label": "Vm",
    "query": {
     "query": "label_values(Vm_price_month,resource_id)"
    }
   },
   {
    "name": "lb_resource_id",
    "label": "LoadBalancer",
    "query": {
     "query": "label_values(LoadBalancer_price_month,resource_id)"
    }
   },
   {
    "name": "vol_resource_id",
    "label": "Volume",
    "query": {
     "query": "label_values(Volume_price_month,resource_id)"
    }
   },
   {
    "name": "snap_resource_id",
    "label": "Snapshot",
    "query": {
     "query": "label_values(Snapshot_price_month,resource_id)"
    }
   },
   {
    "name": "nat_resource_id",
    "label": "NatServices",
    "query": {
     "query": "label_values(NatServices_price_month,resource_id)"
    }
   },
   {
    "name": "ip_resource_id",
    "label": "PublicIp",
    "query": {
     "query": "label_values(PublicIp_price_month,resource_id)"
    }
   },
   {
    "name": "reserved_instance",
    "label": "Reserved Instance",
    "query": "No : 1, 1 Month : 0.7, 1 Year : 0.6, 2 Years : 0.5, 3 Years : 0.4"
   }
  ]
 },
 "panels": [
  {
   "title": "Total cost monthly",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "(sum(Vm_price_month{job=\"osccost-lnf-service\", resource_id=~\"$vm_resource_id\"}*$reserved_instance))+sum(Volume_price_month{job=\"osccost-lnf-service\", resource_id=~\"$vol_resource_id\"})+sum(Snapshot_price_month{job=\"osccost-lnf-service\", resource_id=~\"$snap_resource_id\"})+sum(Snapshot_price_month{job=\"osccost-lnf-service\", resource_id=~\"$snap_resource_id\"})+sum(NatServices_price_month{job=\"osccost-lnf-service\", resource_id=~\"$nat_resource_id\"})",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "Total cost annual",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "((sum(Vm_price_month{job=\"osccost-lnf-service\", resource_id=~\"$vm_resource_id\"}*$reserved_instance))+sum(Volume_price_month{job=\"osccost-lnf-service\", resource_id=~\"$vol_resource_id\"})+sum(Snapshot_price_month{job=\"osccost-service\", resource_id=~\"$snap_resource_id\"})+sum(PublicIp_price_month{job=\"osccost-lnf-service\", resource_id=~\"$ip_resource_id\"}))*12",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "Vm cost",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "(sum(Vm_price_month{job=\"osccost-lnf-service\", resource_id=~\"$vm_resource_id\"}) by (resource_id))*$reserved_instance",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "Vm count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(Vm_price_month{job=\"osccost-lnf-service\", resource_id=~\"$vm_resource_id\"})",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "LoadBalancer cost",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "sum(LoadBalancer_price_month{job=\"osccost-service\", resource_id=~\"$lb_resource_id\"}) by (resource_id)",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "LoadBalancer count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(LoadBalancer_price_month{job=\"osccost-service\", resource_id=~\"$lb_resource_id\"})",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "Volume cost",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "sum(Volume_price_month{job=\"osccost-service\", resource_id=~\"$vol_resource_id\"}) by (resource_id)",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "Volume count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(Volume_price_month{job=\"osccost-service\", resource_id=~\"$vol_resource_id\"})",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "Snapshot cost",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "sum(Snapshot_price_month{job=\"osccost-lnf-service\", resource_id=~\"$snap_resource_id\"}) by (resource_id)",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "Snapshot count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(Snapshot_price_month{job=\"osccost-service\", resource_id=~\"$snap_resource_id\"})",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "NatServices cost",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "sum(NatServices_price_month{job=\"osccost-lnf-service\", resource_id=~\"$nat_resource_id\"}) by (resource_id)",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "NatServices count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(NatServices_price_month{job=\"osccost-service\", resource_id=~\"$nat_resource_id\"})",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "PublicIp cost",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "sum(PublicIp_price_month{job=\"osccost-lnf-service\", resource_id=~\"$ip_resource_id\"}) by (resource_id)",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "PublicIp count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(PublicIp_price_month{job=\"osccost-service\", resource_id=~\"$ip_resource_id\"})",
     "legendFormat": "{{resource_id}}"
    }
   ]
  }
 ]
}